# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Brooke Dolny
# email: brookedolny@gmail.com
title: Brooke Dolny
author:
  name: Brooke Dolny
  email: bmdolny@uwaterloo.ca
description: >- # this means to ignore newlines until "baseurl:"
  Master's of Mathematics at the University of Waterloo. Studying Physics-based Animation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# linkedin_username: brookedolny
# github_username:  brookedolny

# Build settings
markdown: kramdown
# theme: minima
# remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - posts.md
  - about.md

minima:
  skin: dark
  social_links:
    - { platform: github,         user_url: "https://github.com/brookedolny" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/brookedolny" }
    - { platform: twitter,        user_url: "https://twitter.com/brookedolny" }



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
